def getCityDictionary():
	cityDictionary = {
	"Aguascalientes" : "Mexico-Aguascalientes",
	"Baja California" : "Mexico-Baja_California",
	"Baja California Sur" : "Mexico-Baja_California_Sur",
	"Campeche" : "Mexico-Campeche",
	"Chiapas" : "Mexico-Chiapas",
	"Chihuahua" : "Mexico-Chihuahua",
	"Coahuila" : "Mexico-Coahuila_de_Zaragoza",
	"Colima" : "Mexico-Colima",
	"Durango" : "Mexico-Durango",
	"Guanajuato" : "Mexico-Guanajuato",
	"Guerrero" : "Mexico-Guerrero",
	"Hidalgo" : "Mexico-Hidalgo",
	"Jalisco" : "Mexico-Jalisco",
	"Mexico City" : "Mexico-Mexico_City",
	"Michoacán" : "Mexico-Michoacan_de_Ocampo",
	"Morelos" : "Mexico-Morelos",
	"Nayarit" : "Mexico-Nayarit",
	"Nuevo Leon" : "Mexico-Nuevo_Leon",
	"Oaxaca" : "Mexico-Oaxaca",
	"Puebla" : "Mexico-Puebla",
	"Querétaro" : "Mexico-Queretaro_de_Arteaga",
	"Quintana Roo" : "Mexico-Quintana_Roo",
	"San Luis Potosi" : "Mexico-San_Luis_Potosi",
	"Sinaloa" : "Mexico-Sinaloa",
	"Sonora" : "Mexico-Sonora",
	"State of Mexico" : "Mexico-State_Of_Mexico",
	"Tabasco" : "Mexico-Tabasco",
	"Tamaulipas" : "Mexico-Tamaulipas",
	"Tlaxcala" : "Mexico-Tlaxcala",
	"Veracruz" : "Mexico-Veracruz_de_Ignacio_de_la_Llave",
	"Yucatan" : "Mexico-Yucatan",
	"Zacatecas" : "Mexico-Zacatecas"
	}
	return cityDictionary